### ISSUE TITLE
bug(azure): Python 3.14 incompatible with azure-cosmos SDK - TypeError: Session.request() partition_key

### ISSUE THREAD

**Issue by Alan-Jowett** [Alan-Jowett/CoPilot-For-Consensus#1082]
## Description

The embedding service (and potentially all Azure-deployed services using Cosmos DB) fails with:

\\\
TypeError: Session.request() got an unexpected keyword argument 'partition_key'
\\\

This error occurs at \zure_cosmos_document_store.py\ line 565 when calling \container.replace_item()\.

## Root Cause

**Python 3.14 is not officially supported by the azure-cosmos SDK.** The SDK's PyPI classifiers only list Python 3.9 through 3.13. 

Python 3.14 introduced changes to how keyword arguments are forwarded through the HTTP request pipeline, causing the \partition_key\ parameter to leak through to the underlying \
equests.Session.request()\ method.

### How This Happened

1. Dependabot automatically bumped the Python base image from 3.13 to 3.14 (#942, #881)
2. The azure-cosmos SDK (4.x) has not released support for Python 3.14
3. The SDK passes \partition_key\ through its internal HTTP pipeline, which worked in Python 3.13 but breaks in 3.14

## Affected Services

All Azure-deployed services using Cosmos DB via \copilot_storage\ adapter:
- embedding
- parsing  
- chunking
- orchestrator
- summarization
- reporting

## Solution

Downgrade all Azure Dockerfiles from Python 3.14-slim to Python 3.13-slim, which is the latest officially supported version.

## Verification

After deploying with Python 3.13:
1. Check embedding service logs for successful Cosmos DB operations
2. Verify no \Session.request()\ errors in logs
3. Test end-to-end pipeline: ingestion → parsing → chunking → embedding
